/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthBukuKasRouteImport } from './routes/_auth/buku-kas'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthKasirRouteImport } from './routes/_auth/kasir'
import { Route as AuthManajemenKasirRouteImport } from './routes/_auth/manajemen-kasir'
import { Route as AuthProfilRouteImport } from './routes/_auth/profil'
import { Route as AuthProdukIndexRouteImport } from './routes/_auth/produk/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBukuKasRoute = AuthBukuKasRouteImport.update({
  id: '/buku-kas',
  path: '/buku-kas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKasirRoute = AuthKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManajemenKasirRoute = AuthManajemenKasirRouteImport.update({
  id: '/manajemen-kasir',
  path: '/manajemen-kasir',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfilRoute = AuthProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProdukIndexRoute = AuthProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buku-kas': typeof AuthBukuKasRoute
  '/dashboard': typeof AuthDashboardRoute
  '/kasir': typeof AuthKasirRoute
  '/manajemen-kasir': typeof AuthManajemenKasirRoute
  '/profil': typeof AuthProfilRoute
  '/produk/': typeof AuthProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buku-kas': typeof AuthBukuKasRoute
  '/dashboard': typeof AuthDashboardRoute
  '/kasir': typeof AuthKasirRoute
  '/manajemen-kasir': typeof AuthManajemenKasirRoute
  '/profil': typeof AuthProfilRoute
  '/produk': typeof AuthProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/buku-kas': typeof AuthBukuKasRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/kasir': typeof AuthKasirRoute
  '/_auth/manajemen-kasir': typeof AuthManajemenKasirRoute
  '/_auth/profil': typeof AuthProfilRoute
  '/_auth/produk/': typeof AuthProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/buku-kas'
    | '/dashboard'
    | '/kasir'
    | '/manajemen-kasir'
    | '/profil'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/buku-kas'
    | '/dashboard'
    | '/kasir'
    | '/manajemen-kasir'
    | '/profil'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/buku-kas'
    | '/_auth/dashboard'
    | '/_auth/kasir'
    | '/_auth/manajemen-kasir'
    | '/_auth/profil'
    | '/_auth/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/buku-kas': {
      id: '/_auth/buku-kas'
      path: '/buku-kas'
      fullPath: '/buku-kas'
      preLoaderRoute: typeof AuthBukuKasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kasir': {
      id: '/_auth/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof AuthKasirRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/manajemen-kasir': {
      id: '/_auth/manajemen-kasir'
      path: '/manajemen-kasir'
      fullPath: '/manajemen-kasir'
      preLoaderRoute: typeof AuthManajemenKasirRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profil': {
      id: '/_auth/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthProfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/produk/': {
      id: '/_auth/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof AuthProdukIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthBukuKasRoute: typeof AuthBukuKasRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthKasirRoute: typeof AuthKasirRoute
  AuthManajemenKasirRoute: typeof AuthManajemenKasirRoute
  AuthProfilRoute: typeof AuthProfilRoute
  AuthProdukIndexRoute: typeof AuthProdukIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBukuKasRoute: AuthBukuKasRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthKasirRoute: AuthKasirRoute,
  AuthManajemenKasirRoute: AuthManajemenKasirRoute,
  AuthProfilRoute: AuthProfilRoute,
  AuthProdukIndexRoute: AuthProdukIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
