/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCashbookRouteImport } from './routes/_auth/cashbook'
import { Route as AuthCashierRouteImport } from './routes/_auth/cashier'
import { Route as AuthCashierManagementRouteImport } from './routes/_auth/cashier-management'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthProductIndexRouteImport } from './routes/_auth/product/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCashbookRoute = AuthCashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCashierRoute = AuthCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCashierManagementRoute = AuthCashierManagementRouteImport.update({
  id: '/cashier-management',
  path: '/cashier-management',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductIndexRoute = AuthProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cashbook': typeof AuthCashbookRoute
  '/cashier': typeof AuthCashierRoute
  '/cashier-management': typeof AuthCashierManagementRoute
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/product/': typeof AuthProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cashbook': typeof AuthCashbookRoute
  '/cashier': typeof AuthCashierRoute
  '/cashier-management': typeof AuthCashierManagementRoute
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/product': typeof AuthProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/cashbook': typeof AuthCashbookRoute
  '/_auth/cashier': typeof AuthCashierRoute
  '/_auth/cashier-management': typeof AuthCashierManagementRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/product/': typeof AuthProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cashbook'
    | '/cashier'
    | '/cashier-management'
    | '/dashboard'
    | '/profile'
    | '/product/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cashbook'
    | '/cashier'
    | '/cashier-management'
    | '/dashboard'
    | '/profile'
    | '/product'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/cashbook'
    | '/_auth/cashier'
    | '/_auth/cashier-management'
    | '/_auth/dashboard'
    | '/_auth/profile'
    | '/_auth/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/cashbook': {
      id: '/_auth/cashbook'
      path: '/cashbook'
      fullPath: '/cashbook'
      preLoaderRoute: typeof AuthCashbookRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cashier': {
      id: '/_auth/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AuthCashierRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cashier-management': {
      id: '/_auth/cashier-management'
      path: '/cashier-management'
      fullPath: '/cashier-management'
      preLoaderRoute: typeof AuthCashierManagementRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/product/': {
      id: '/_auth/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof AuthProductIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCashbookRoute: typeof AuthCashbookRoute
  AuthCashierRoute: typeof AuthCashierRoute
  AuthCashierManagementRoute: typeof AuthCashierManagementRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthProductIndexRoute: typeof AuthProductIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCashbookRoute: AuthCashbookRoute,
  AuthCashierRoute: AuthCashierRoute,
  AuthCashierManagementRoute: AuthCashierManagementRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthProductIndexRoute: AuthProductIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
